# Use the Hyde theme via the Remote Theme plugin
remote_theme: poole/hyde

# Essential Plugins (needed for Hyde to work correctly on GitHub Pages)
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-gist
# Make the sidebar green
layout_class: theme-base-0b

# Site settings
title: PingLo 
logo: public/css/logo.svg
description: Small website to share information about PingLo.
baseurl: "" # The subpath of your site, e.g. /project-name/ (leave empty if using username.github.io)
url: "https://alpakk4.github.io" # Your site's URL

# Hyde specific settings
paginate: 5
version: 1.0
